# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 012432013bf22523e351610e1de81850c5cd96618e5a0ee9a528ceed5d19773142b8000956c3d55a454cbe84f02e9d42fd201adaac5731cde890eea8a049f37c

test:
  secret_key_base: 2e25b1859858a773ba1429e2fc57dcaa641e1670b4ec572038c119055613597b45a586bc8f2f7fd4a5b6c43e169d3d8a6f5e4a4535a10ec314f499e6dd5b18b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
